[tox]
envlist = py312, py313, py314, flake8

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
allowlist_externals=
    uv
commands_pre=
    uv sync --group test --all-extras
commands = pytest {posargs}
extras = intake-esm
         elasticsearch

[flake8]
ignore = E501, W503
extend-ignore = E203
exclude =
    docs,
    __pycache__,
    .git

[isort]
profile=black
